#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SPEC_PATH="${SCRIPT_DIR}/buildozer.spec"
BUILD_INFO_PATH="${SCRIPT_DIR}/build_info.py"
KEYSTORE_PATH="${SCRIPT_DIR}/psyke-upload.keystore"
LOG_PATH="${SCRIPT_DIR}/buildozer-aab.log"
OUT_DIR="${REPO_ROOT}/ABB"
OUT_FILE="${OUT_DIR}/ABB-V5.aab"

test -n "${ANDROID_KEYSTORE_BASE64:-}"
test -n "${ANDROID_KEYSTORE_PASSWORD:-}"
test -n "${ANDROID_KEY_ALIAS:-}"
test -n "${ANDROID_KEY_PASSWORD:-}"

printf '%s' "${ANDROID_KEYSTORE_BASE64}" | base64 --decode > "${KEYSTORE_PATH}"

export SPEC_PATH BUILD_INFO_PATH KEYSTORE_PATH
python - <<'PY'
from __future__ import annotations

import datetime as dt
import os
import re
from pathlib import Path

spec_path = Path(os.environ["SPEC_PATH"])
build_info_path = Path(os.environ["BUILD_INFO_PATH"])
keystore_path = Path(os.environ["KEYSTORE_PATH"])
spec = spec_path.read_text(encoding="utf-8")

match = re.search(r"(?m)^version\s*=\s*(.+?)\s*$", spec)
default_version = match.group(1).strip() if match else "8.0.0"
version = (os.environ.get("INPUT_VERSION") or "").strip() or default_version
run_no = int(os.environ.get("GITHUB_RUN_NUMBER", "0") or "0")
# Use UTC epoch seconds so each CI build gets a fresh Play-safe versionCode.
# (Valid until 2038 under Android's signed-int limit.)
numeric = int(dt.datetime.now(dt.timezone.utc).timestamp())

def upsert(text: str, key: str, value: str) -> str:
    pattern = rf"(?m)^{re.escape(key)}\s*=.*$"
    line = f"{key} = {value}"
    if re.search(pattern, text):
        return re.sub(pattern, line, text)
    if not text.endswith("\n"):
        text += "\n"
    return text + line + "\n"

spec = upsert(spec, "version", version)
spec = upsert(spec, "android.numeric_version", str(numeric))
spec = upsert(spec, "android.release_artifact", "aab")
spec = upsert(spec, "android.keystore", keystore_path.name)
spec = upsert(spec, "android.keystore_passwd", os.environ["ANDROID_KEYSTORE_PASSWORD"])
spec = upsert(spec, "android.keyalias", os.environ["ANDROID_KEY_ALIAS"])
spec = upsert(spec, "android.keyalias_passwd", os.environ["ANDROID_KEY_PASSWORD"])
spec_path.write_text(spec, encoding="utf-8")

sha = os.environ.get("GITHUB_SHA", "")[:7] or "unknown"
now = dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
build_info = (
    '"""Auto-generated by CI. Do not edit in artifacts."""\n\n'
    f'APP_VERSION = {version!r}\n'
    f'BUILD_SHA = {sha!r}\n'
    f'BUILD_DATE_UTC = {now!r}\n'
    f'BUILD_RUN = {str(run_no)!r}\n'
)
build_info_path.write_text(build_info, encoding="utf-8")
print(f"Stamped version={version} numeric={numeric} sha={sha} run={run_no}")
PY

cd "${SCRIPT_DIR}"
buildozer -v android release 2>&1 | tee "${LOG_PATH}"

mkdir -p "${OUT_DIR}"
rm -f "${OUT_FILE}"

AAB_PATH="$(find "${SCRIPT_DIR}/bin" -maxdepth 1 -type f -name '*.aab' | head -n 1)"
test -n "${AAB_PATH}"

jarsigner \
  -keystore "${KEYSTORE_PATH}" \
  -storepass "${ANDROID_KEYSTORE_PASSWORD}" \
  -keypass "${ANDROID_KEY_PASSWORD}" \
  "${AAB_PATH}" \
  "${ANDROID_KEY_ALIAS}"

jarsigner -verify -verbose -certs "${AAB_PATH}"
cp "${AAB_PATH}" "${OUT_FILE}"

rm -f "${KEYSTORE_PATH}"
